jwt:
  secretKey: aasdlaksfjlaksfjklasjfklasjfklasjfkatympasfkajflkasfakslfjaklsfasfa

#  access:
#    expiration: 3600000 # 1시간(60분) (1000L(ms -> s) * 60L(s -> m) * 60L(m -> h))
#    header: Authorization
#
#  refresh:
#    expiration: 1209600000 #  (1000L(ms -> s) * 60L(s -> m) * 60L(m -> h) * 24L(h -> 하루) * 14(2주))
#    header: Authorization-refresh
  access:
    expiration: 86400000 # 1일(24시간) (1000L(ms -> s) * 60L(s -> m) * 60L(m -> h) * 24L(h -> 하루))
    header: Authorization

  refresh:
    expiration: 2592000000 # 1달(30일) (1000L(ms -> s) * 60L(s -> m) * 60L(m -> h) * 24L(h -> 하루) * 30(하루 수))
    header: Authorization-refresh

cloud:
  aws:
    s3:
      bucket: dongnaefit-bucket
    credentials:
      access-key: AKIAXWMA6IURINZHWYWC
      secret-key: 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
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

spring:
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:mysql://dongnaefit-db.c78gaoqkcicz.ap-northeast-2.rds.amazonaws.com:3306/dongnaefit_DB
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: younjeong
    password: dbswjd6654
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 50
        dialect: org.hibernate.dialect.MySQLDialect